#make /home/cmp408/tools/arm-bcm2708/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc piiotest.c
all: piiotest.c
	/home/cmp408/tools/arm-bcm2708/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -g -Wall -o piiotest piiotest.c

clean: 
	$(RM) piiotest
